### ISSUE TITLE
Issue with cards on home page

### ISSUE THREAD

**Issue by peterdesmet** [echinopscis/echinopscis.github.io#15]
Hi @nickynicolson, I'm trying to figure out why the blog posts on the home page are squeezed and whether that is an issue with petridish

<img width="929" alt="Screenshot 2022-10-17 at 09 01 17" src="https://user-images.githubusercontent.com/600993/196110262-9dbb154d-378a-4220-b565-976418b30082.png">

It looks like the HTML is:

```
<div class="row cards mt-4">
  <div class="col-md-6">
    <div class="card">
  </div>
  <div class="col-md-6">
    <div class="card">
    <div class="col-md-6">
      <div class="card">
    </div>
  </div>
</div>
```

While it should be:

```
<div class="row cards mt-4">
  <div class="col-md-6">
    <div class="card">
  </div>
  <div class="col-md-6">
    <div class="card">
  </div>
  <div class="col-md-6">
    <div class="card">
  </div>
</div>
```

It almost looks like a `</div>` is not closed properly in one of the posts.

**Comment by peterdesmet** [comment]
A stray `</div>` in one of the _layouts would also explain why the blog posts are not displayed in rows at https://echinopscis.github.io/blog/

**Comment by peterdesmet** [comment]
This was an issue with petridish. When the page/post `description` contained a div, it rendered incorrectly as a card (https://github.com/peterdesmet/petridish/issues/57).

This is now fixed in petridish and will be part of an upcoming v2.1.

I'm leaving this issue open for you, as a reminder to migrate to petridish@v2.1 once it is ready:

https://github.com/echinopscis/echinopscis.github.io/blob/a4317ae6de53401eeb04340f72a54cf08e5f19cd/_config.yml#L8

**Comment by nickynicolson** [comment]
Updated theme
https://github.com/echinopscis/echinopscis.github.io/blob/cd00edd2646b0b582482f82993009ef67f0f018b/_config.yml#L12
